[package]
name = "twitchtv-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow       = "1"
directories  = "6.0.0"
rayon        = "1.8"
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
toml         = "0.9.2"
which        = "8.0.0"
dialoguer    = "0.11"
